name: openshot-community
version: '3.1.1'
summary: OpenShot video editor
description:  OpenShot Video Editor is a free, open-source, non-linear video editor. It can create and edit videos and movies using many popular video, audio, and image formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many more common formats!

grade: stable
confinement: strict
base: core22

compression: lzo
architectures:
  - build-on: amd64

package-repositories:
 - type: apt
   ppa: openshot.developers/ppa

environment:
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages${PYTHONPATH:+:$PYTHONPATH}
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}
  QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP/lib/$CRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP_DESKTOP_RUNTIME/lib/$CRAFT_ARCH_TRIPLET${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}
  LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/dri${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  DISABLE_WAYLAND: 1
  QTWEBENGINEPROCESS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/libexec/QtWebEngineProcess
  HOME: $SNAP_USER_COMMON
  ALSA_CONFIG_PATH: $SNAP/usr/share/alsa/alsa.conf
  ALWAYS_USE_PULSEAUDIO: '1'

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  openshot:
    after: [alsa-mixin]
    plugin: nil
    stage-packages:
      - openshot-qt
      - python3-openshot
      - libqt5webenginecore5
      - libglu1-mesa
    override-build: |
      craftctl default
      sed -i 's|Icon=openshot-qt|Icon=/usr/share/icons/hicolor/scalable/apps/openshot-qt.svg|' ${CRAFT_PART_INSTALL}/usr/share/applications/org.openshot.OpenShot.desktop
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      
apps:
  openshot-community:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: usr/bin/openshot-qt
    desktop: usr/share/applications/org.openshot.OpenShot.desktop
    extensions: [ gnome ]
    plugs:
      - home
      - removable-media
      - audio-playback
      - opengl
      - network-bind
      - shmem
      - alsa
      
plugs:
  shmem:
    interface: shared-memory
    private: true

